ExamenFinal/FactoringEmpresa.Web/Controllers/EmpresaController.cs
using FactoringEmpresa.Web.Funcionalidades.ListarEmpresas;
using FactoringEmpresa.Web.Funcionalidades.RegistrarEmpresa;
using IdentitySample.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;

namespace FactoringEmpresa.Web.Controllers
{
    [Authorize]
    public class EmpresaController : Controller
    {
        // GET: Empresa
        public ActionResult Lista()
        {
            using (var listarEmpresas = new ListarEmpresasHandler())
            {
                return View(listarEmpresas.Ejecutar(User.Identity.Name));
            }
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View(new RegistrarEmpresaViewModel());
        }

        [HttpPost]
        public ActionResult Registrar(RegistrarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);
            
            using (var registrarEmpresa = new RegistrarEmpresaHandler())
            {
                try
                {   
                    registrarEmpresa.Ejecutar(modelo, User.Identity.Name);
                    return RedirectToAction("Lista");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }

        [HttpGet]
        public PartialViewResult Editar(string id)
        {
            using (var buscarEmpresa = new VerUnaEmpresaHandler())
            {
                return PartialView("_Editar", buscarEmpresa.Execute(id));
            }
        }
        [HttpPost]
        public ActionResult Editar(VerUnaEmpresaViewModel model)
        {
            return RedirectToAction("Lista");
        }

        [HttpGet]
        public PartialViewResult Eliminar(string id)
        {
            using (var buscarEmpresa = new VerUnaEmpresaHandler())
            {
                return PartialView("_Eliminar", buscarEmpresa.Execute(id));
            }
        }

        [HttpPost]
        public ActionResult Eliminar(VerUnaEmpresaViewModel model)
        {
            return RedirectToAction("Lista");
        }

    }
}

ExamenFinal/FactoringEmpresa.Web/Controllers/FacturaController.cs
using FactoringEmpresa.Web.Funcionalidades.ListarFacturasXEmpresas;
using FactoringEmpresa.Web.Funcionalidades.RegistrarFacturaXEmpresa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FactoringEmpresa.Web.Controllers
{
    [Authorize]
    public class FacturaController : Controller
    {
        // GET: Factura
        public ActionResult Lista(string id)
        {
            using (var listarFacturas = new ListarFacturasXEmpresaHandler())
            {
                return View(listarFacturas.Ejecutar(id));
            }
        }

        [HttpGet]
        public PartialViewResult Registrar(string id, string empresa)
        {
            return PartialView("_Registrar", new RegistrarFacturaXEmpresaViewModel()
            {
                RucEmpresa = id,
                RazonSocial = empresa
            });
        }

        [HttpPost]
        public ActionResult Registrar(RegistrarFacturaXEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var registrarFactura = new RegistrarFacturaXEmpresaHandler())
            {
                try
                {
                    registrarFactura.Ejecutar(modelo);
                    return RedirectToAction("Lista", "Empresa");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }
    }
}

ExamenFinal/FactoringEmpresa.Web/Views/Empresa/Lista.cshtml
@model IEnumerable<FactoringEmpresa.Web.Funcionalidades.ListarEmpresas.ListaEmpresasViewModel>

@{
    ViewBag.Title = "Empresas";
}

<h2>Empresas</h2>

<p>
    @Html.ActionLink("Create New", "Registrar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ruc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rubro)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ruc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RazonSocial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rubro)
        </td>
        <td>
            <div class="btn-group">
                <button class="btn dropdown-toggle btn-xs"
                        data-toggle="dropdown">
                    <span>
                        <i class="glyphicon glyphicon-collapse-down"></i>
                        <span class="caret"></span>
                    </span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        @Ajax.ActionLink(" Editar", "Editar", "Empresa"
                   , new { id = item.Ruc }
                   , new AjaxOptions
                   {
                       HttpMethod = "Get",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "EditarEmpresaForm"
                   }
                   ,
                   new
                   {
                       data_toggle = "modal",
                       data_target = "#EditarEmpresaForm",
                       @class = "glyphicon glyphicon-pencil"
                   }
                   )
                    </li>                    
                    <li>
                        @Ajax.ActionLink(" Eliminar", "Eliminar", "Empresa"
                   , new { id = item.Ruc }
                   , new AjaxOptions
                   {
                       HttpMethod = "Get",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "EliminarEmpresaForm"
                   }
                   ,
                   new
                   {
                       data_toggle = "modal",
                       data_target = "#EliminarEmpresaForm",
                       @class = "glyphicon glyphicon-trash"
                   })
                    </li>
                    <li><span>====================</span></li>
                    <li>
                        @Ajax.ActionLink("Nueva Factura", "Registrar", "Factura"
                   , new {
                       id = item.Ruc,
                       empresa = item.RazonSocial
                   }
                   , new AjaxOptions
                   {
                       HttpMethod = "Get",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "NuevaFacturaEmpresaForm"
                   }
                   ,
                   new
                   {
                       data_toggle = "modal",
                       data_target = "#NuevaFacturaEmpresaForm"
                   })
                    </li>
                    <li>
                        @Ajax.ActionLink("Ver Facturas", "Lista","Factura", new { id = item.Ruc }, new AjaxOptions { HttpMethod = "Get" })
                    </li>
                </ul>
            </div>
        </td>
    </tr>
}
</table>


<div id="EditarEmpresaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EditarEmpresalabel"
     aria-hidden="true">
</div>

<div id="EliminarEmpresaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="EliminarEmpresalabel"
     aria-hidden="true">
</div>

<div id="NuevaFacturaEmpresaForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="NuevaFacturaEmpresalabel"
     aria-hidden="true">
</div>


@section Scripts{
    @Scripts.Render("~/bundles/unobtrusiveajax")
}

ExamenFinal/FactoringEmpresa.Web/Views/Empresa/Registrar.cshtml
@model FactoringEmpresa.Web.Funcionalidades.RegistrarEmpresa.RegistrarEmpresaViewModel

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegistrarEmpresaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ruc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ruc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ruc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rubro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rubro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rubro, "", new { @class = "text-danger" })
            </div>
        </div>
        <!-- Seccion de listas en cascada -->
        <div id="empresa-ubigeo">
            <div class="form-group">
                @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.HiddenFor(model => model.Departamento, new { @id = "departamento_nombre", @class = "departamento" })
                    @Html.DropDownList("departamento", Model.Departamentos,
                        new { @id = "empresa_departamento", @class = "form-control departamento" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.HiddenFor(model => model.Provincia, new { @id = "provincia_nombre", @class = "provincia" })
                    @Html.DropDownList("provincia", Model.Provincias,
                        new { @id = "empresa_provincia", @class = "form-control provincia" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.HiddenFor(model => model.Distrito, new { @id = "distrito_nombre", @class = "distrito" })
                    @Html.DropDownList("distrito", Model.Distritos,
                        new { @id = "empresa_distrito", @class = "form-control distrito" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/registraempresa")

}

ExamenFinal/FactoringEmpresa.Web/Views/Empresa/_Editar.cshtml
@model FactoringEmpresa.Web.Funcionalidades.ListarEmpresas.VerUnaEmpresaViewModel

<div id="VerEmpresa">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Ruc, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.Ruc, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Rubro, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Rubro, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Rubro, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Departamento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Distrito, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ExamenFinal/FactoringEmpresa.Web/Views/Empresa/_Eliminar.cshtml
@model FactoringEmpresa.Web.Funcionalidades.ListarEmpresas.VerUnaEmpresaViewModel

<div id="VerEmpresa">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="alert alert-danger " role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        ¿Estás seguro de eliminar este registro?
                    </div>
                </div>
                <div class="modal-body">

                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Ruc)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Ruc)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.RazonSocial)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.RazonSocial)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Direccion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Direccion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Rubro)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Rubro)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Departamento)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Departamento)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Provincia)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Provincia)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Distrito)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Distrito)
                        </dd>

                    </dl>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>